version: '3.8'
services:
  loader:
    container_name: loader
    build:
      context: .
    volumes:
      - .:/app
      # Volume abaixo é para ambiente em container, apontar o caminho e nome do certificado de .env
      #- "${PATH_CERTS}/${NAME_CERTS}:/root/.certs/${NAME_CERTS}:ro" # Caminho padrão container /root/.certs
    ports:
      - "80:8000"
    networks:
      - network_app
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
      DEBUG: "${DEBUG}"
    working_dir: /app
    command: >
      bash -c "python manage.py migrate &&
               python manage.py makemigrations &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000 --insecure"
    restart: unless-stopped

volumes:
  app:

networks:
  network_app:
